spring:
  #mysql
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/test?serverTimezone=UTC&&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 1234

  #devtools
  devtools:
    livereload:
      enabled: true

  #jsp
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # jsp파일 reload할때마다 재부팅해야되서 해당설정 추가
  server:
    servlet:
      jsp:
        init-parameters:
          development: true

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: th/*

#server port
server:
  port: 8080

# mybatis 설정.
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml